name: Frontend App Workflow

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/frontend-app.yml
      - ./**

  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/frontend-app.yml
      - ./**

jobs:
  lint:
    name: Lint & build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Lint frontend app
        run: yarn lint

      - name: Build static UI
        run: yarn build
